# Generated by Django 5.0.1 on 2025-12-07 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Nombre del icono Lucide', max_length=50)),
                ('color', models.CharField(default='#000000', help_text='Color en formato hex', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Nombre del icono', max_length=50)),
                ('category', models.CharField(choices=[('amenity', 'Amenidad'), ('accessibility', 'Accesibilidad'), ('payment', 'Métodos de Pago'), ('service', 'Servicio')], default='amenity', max_length=50)),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(max_length=200, verbose_name='Descripción corta')),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Barrio')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('hours', models.JSONField(blank=True, default=dict, help_text='Horarios de atención')),
                ('is_open_24h', models.BooleanField(default=False, verbose_name='Abierto 24h')),
                ('price_range', models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], default=2, verbose_name='Rango de precio')),
                ('images', models.JSONField(blank=True, default=list, help_text='URLs de imágenes')),
                ('cover_image', models.URLField(verbose_name='Imagen de portada')),
                ('logo', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Rating')),
                ('review_count', models.IntegerField(default=0, verbose_name='Cantidad de reseñas')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('claimed', models.BooleanField(default=False, verbose_name='Reclamado')),
                ('views', models.IntegerField(default=0)),
                ('favorites_count', models.IntegerField(default=0)),
                ('visits_count', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='businesses.category')),
                ('features', models.ManyToManyField(blank=True, related_name='businesses', to='businesses.feature')),
                ('tags', models.ManyToManyField(blank=True, related_name='businesses', to='businesses.tag')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'db_table': 'businesses',
                'ordering': ['-rating', '-review_count'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='businesses.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='businesses.business')),
            ],
            options={
                'db_table': 'visits',
                'ordering': ['-visited_at'],
            },
        ),
    ]
