# Generated by Django 5.0.1 on 2025-12-07 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route'),
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'business')},
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category', 'neighborhood'], name='businesses_categor_2a9034_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['rating', '-created_at'], name='businesses_rating_63e07f_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['latitude', 'longitude'], name='businesses_latitud_a1cf4f_idx'),
        ),
    ]
